# fly.toml app configuration file generated for vaadin-nps on 2024-11-04T08:46:09-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'vaadin-nps'
primary_region = 'sjc'

[build]
dockerfile = 'Dockerfile'

[env]
SPRING_PROFILES_ACTIVE = 'prod'

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 1
processes = ['app']

[[vm]]
memory = '2gb'
cpu_kind = 'shared'
cpus = 1
