# overlays/prod/kustomization.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - secrets.yaml  # Production-specific secrets

patchesStrategicMerge:
  - patches/configmap.yaml
  - patches/deployment.yaml
  - patches/ingress.yaml