apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # Production API server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address for expiry notifications
    email: marcus@vaadin.com  # Change this!
    privateKeySecretRef:
      name: letsencrypt-prod-key
    solvers:
      - http01:
          ingress:
            class: nginx  # Must match your ingress class