apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - secrets.yaml

namespace: nps-dev

commonLabels:
  environment: development

patches:
  # Update the ingress for local development
  - target:
      kind: Ingress
      name: nps-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: nps.lvh.me

  # Update ConfigMap for local URL
  - target:
      kind: ConfigMap
      name: nps
    patch: |-
      - op: replace
        path: /data/BASE_URL
        value: "http://nps.lvh.me"


  # Update deployment for local development
  - target:
      kind: Deployment
      name: nps
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: nps:local
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY
          value: "DEBUG"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY_OAUTH2
          value: "TRACE"